# Generated by Django 2.2.17 on 2020-11-17 13:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0005_create_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 19, 13, 59, 18, 433092, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
